### ISSUE TITLE
Question: impl functions on Type and ArchivedType

### ISSUE THREAD

**Issue by Firestar99** [rkyv/rkyv#512] opened 2024-07-12 17:49 UTC
I've commonly ran across the use-case where I would like to impl some functions for both the normal `Type` and `ArchivedType`. But how should you implement something for both traits, without just copy-pasting them?

May there be a way to create an `ArchivedType` from a plain `Type` reference, without having to serialize / create a separate intermediary buffer, to then forward all calls from `Type` to `ArchivedType`'s impl?

Right now I'm usually just passing all fields as references to a 3rd standalone method, to abstract away whether it's an archived type or not, but this isn't exactly a good solution.

**Comment by djkoloski** [comment] 2024-08-11 22:16
I don't have a good answer for this one unfortunately. A while ago I tried to unify archived and un-archived types with [rel](https://github.com/rkyv/rel), but that ended up being too much work and complexity to continue to put effort into. The main options are:

1. Unify through a common trait. This has the downside of making all of your code generic.
2. Unify through an enum. This has the downside of making everything more complicated.
3. Duplicate all of your inherent impls via macro. This has the downside of duplicating code and making everything more complicated.
4. Unify your archived and unarchived types. This has the downside that you have to change your type to support specific endianness, and that it can't support types with relative pointers (which is kind of the whole point of rkyv).

Whichever route you think is best for your specific situation is up to you. I don't have a good way to solve it right now.

**Comment by djkoloski** [comment] 2024-08-11 22:31
Closing as dupe of #167

**Closed by djkoloski** 2024-08-11 22:31 UTC
