### ISSUE TITLE
Enum with custom discriminator incorrectly returned with `#[archive(as = "Self")`

### ISSUE THREAD

**Issue by athre0z** [rkyv/rkyv#445] opened 2023-12-08 12:03 UTC
The following reproducer test case:

```diff
diff --git a/rkyv_test/src/test_alloc.rs b/rkyv_test/src/test_alloc.rs
index 93840cc..65bcf7d 100644
--- a/rkyv_test/src/test_alloc.rs
+++ b/rkyv_test/src/test_alloc.rs
@@ -1405,6 +1405,20 @@ mod tests {
         let value = ExampleEnum::A("hello world".to_string());

         test_archive(&value);
+
+        // Int enum
+
+        #[derive(Archive, Serialize, Deserialize, Debug, PartialEq)]
+        #[archive(as = "ExampleIntEnum")]
+        #[repr(u8)]
+        enum ExampleIntEnum {
+            Foo = 1,
+            Bar,
+        }
+
+        let value = ExampleIntEnum::Bar;
+
+        test_archive(&value);
     }

     mod with {
````

currently fails with:

```
---- test_alloc::tests::archive_as stdout ----
thread 'test_alloc::tests::archive_as' panicked at rkyv_test/src/util.rs:91:5:
assertion `left == right` failed
  left: Foo
 right: Bar
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Corresponding `cargo expand` output:

```rust
#[archive(as = "ExampleIntEnum")]
#[repr(u8)]
enum ExampleIntEnum {
    Foo = 1,
    Bar,
}
#[automatically_derived]
///The resolver for an archived [`ExampleIntEnum`]
enum ExampleIntEnumResolver {
    ///The resolver for [`ExampleIntEnum::Foo`]
    #[allow(dead_code)]
    Foo,
    ///The resolver for [`ExampleIntEnum::Bar`]
    #[allow(dead_code)]
    Bar,
}
#[automatically_derived]
const _: () = {
    use core::marker::PhantomData;
    use ::rkyv::{out_field, Archive, Archived};
    #[repr(u8)]
    enum ArchivedTag {
        Foo = 0u8,
        Bar = 1u8,
    }
    impl Archive for ExampleIntEnum {
        type Archived = ExampleIntEnum;
        type Resolver = ExampleIntEnumResolver;
        #[allow(clippy::unit_arg)]
        #[inline]
        unsafe fn resolve(
            &self,
            pos: usize,
            resolver: <Self as Archive>::Resolver,
            out: *mut <Self as Archive>::Archived,
        ) {
            match resolver {
                ExampleIntEnumResolver::Foo => {
                    out.cast::<ArchivedTag>().write(ArchivedTag::Foo);
                }
                ExampleIntEnumResolver::Bar => {
                    out.cast::<ArchivedTag>().write(ArchivedTag::Bar);
                }
            }
        }
    }
};
#[automatically_derived]
const _: () = {
    use ::rkyv::{Archive, Fallible, Serialize};
    impl<__S: Fallible + ?Sized> Serialize<__S> for ExampleIntEnum {
        #[inline]
        fn serialize(
            &self,
            serializer: &mut __S,
        ) -> ::core::result::Result<
            <Self as Archive>::Resolver,
            __S::Error,
        > {
            Ok(
                match self {
                    Self::Foo => ExampleIntEnumResolver::Foo,
                    Self::Bar => ExampleIntEnumResolver::Bar,
                },
            )
        }
    }
};
#[automatically_derived]
const _: () = {
    use ::rkyv::{Archive, Archived, Deserialize, Fallible};
    impl<__D: Fallible + ?Sized> Deserialize<ExampleIntEnum, __D>
    for Archived<ExampleIntEnum> {
        #[inline]
        fn deserialize(
            &self,
            deserializer: &mut __D,
        ) -> ::core::result::Result<ExampleIntEnum, __D::Error> {
            Ok(
                match self {
                    Self::Foo => ExampleIntEnum::Foo,
                    Self::Bar => ExampleIntEnum::Bar,
                },
            )
        }
    }
};
```

I'm not completely familiar with rkyv's internals yet, but it I'm **guessing** that is might be related to the fact that the generated `ExampleIntEnumResolver` and/or `ArchivedTag` types don't use the custom discriminators and that some code just reinterprets the tag/resolver enum to the `as` type, which doesn't work out.

**Comment by djkoloski** [comment] 2024-03-10 00:58
Dupe of #285

**Closed by djkoloski** 2024-03-10 00:58 UTC
