### ISSUE TITLE
`thiserror` wants transparent errors to be Send+Sync

### ISSUE THREAD

**Issue by leontoeides** [rkyv/rkyv#320] opened 2022-10-16 02:15 UTC
`rkyv::validation::CheckArchiveError` doesn't seem to play nice with `thiserror` crate because it is not `Send`+`Sync`

**Comment by djkoloski** [comment] 2022-11-14 23:30
Could you provide the full type of `CheckArchiveError`? That type is generic so it should be `Send + Sync` as long as its type arguments are. I see manual impls for `ArchiveError` so I'm not sure of the source of the lacking impl.

**Comment by leontoeides** [comment] 2022-11-16 16:06
Hello sorry for the delay. The is the issue I was having using rkyv with thiserror. My current solution is to convert it to a string. I'm not sure if this means anything to you:

```
error[E0277]: `(dyn bytecheck::Error + 'static)` cannot be sent between threads safely
   --> 
    |
62  |             .try_for_each(|element| {
    |              ^^^^^^^^^^^^ `(dyn bytecheck::Error + 'static)` cannot be sent between threads safely
    |
    = help: the trait `std::marker::Send` is not implemented for `(dyn bytecheck::Error + 'static)`
    = note: required for `Unique<(dyn bytecheck::Error + 'static)>` to implement `std::marker::Send`
    = note: required because it appears within the type `Box<(dyn bytecheck::Error + 'static)>`
    = note: required because it appears within the type `StructCheckError`
    = note: required because it appears within the type `CheckArchiveError<StructCheckError, DefaultValidatorError>`
```

**Comment by djkoloski** [comment] 2022-11-16 16:12
Thanks for clarifying, that helps a lot. It looks like the issue is that `bytecheck` doesn't require its error types to be `Send + Sync`. I've filed a bug against `bytecheck` for this feature (which would require a breaking change): https://github.com/rkyv/bytecheck/issues/25.

Closing this one since it's been moved.

**Closed by djkoloski** 2022-11-16 16:12 UTC
