### ISSUE TITLE
Switching from `String` to `Box<str>` causes small archived strings to become larger.

### ISSUE THREAD

**Issue by eievui5** [rkyv/rkyv#524] opened 2024-08-19 01:44 UTC
I noticed that when I switch from `String` to `Box<str>`, my archives get *larger* rather than smaller (like a `String` does in memory). https://docs.rs/rkyv/latest/rkyv/string/struct.ArchivedString.html seems to have an inlining optimization for small strings; would it be possible to special-case `Box<str>`'s implementation as well so that there isn't a tradeoff?

**Comment by djkoloski** [comment] 2024-08-19 01:49
`Box`'s `Archive` impl is generic over all boxed types, and so can't perform a small-string optimization the way `ArchivedString` can since that would require specialization. If you just want `Box<str>` to serialize as and deserialize from `ArchivedString` to benefit from SSO, you can use a wrapper type to do the conversion. See [the `ArchiveWith` docs](https://docs.rs/rkyv/latest/rkyv/with/trait.ArchiveWith.html) for an example.

**Comment by djkoloski** [comment] 2024-09-01 20:16
Closing this since we can't special-case `Box<str>`, there are a few other workarounds available, and this is expected behavior.

**Closed by djkoloski** 2024-09-01 20:16 UTC
